tasks_rest:
    type: rest
    prefix: /api
    resource: "@GerWorkflowBundle/Resources/config/routing/task_routes.yml"

hosts_rest:
    type: rest
    prefix: /api
    resource: "@GerWorkflowBundle/Resources/config/routing/host_routes.yml"

steps_rest:
    type: rest
    prefix: /api
    resource: "@GerWorkflowBundle/Resources/config/routing/step_routes.yml"

workers_rest:
    type: rest
    prefix: /api
    resource: "@GerWorkflowBundle/Resources/config/routing/worker_routes.yml"

workflows_rest:
    type: rest
    prefix: /api
    resource: "@GerWorkflowBundle/Resources/config/routing/workflow_routes.yml"