services:
    ger_worklow_bundle.form.type.worflow:
        class: Ger\Bundle\WorkflowBundle\Form\Type\WorkflowType
        tags:
            - { name: form.type, alias: ger_workflow }

    ger_api.event.authentication_success_listener:
        class: Ger\Bundle\WorkflowBundle\EventListener\AuthenticationSuccessListener
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }