workflows:
    type: rest  # Required for `RestYamlLoader` to process imported routes
    prefix: /api
    resource: "@GerWorkflowBundle/Resources/config/workflow_routes.yml"

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc
